version: '3'
volumes:
    dados:
networks:
    banco:
    web:
    fila:
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=db
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - banco
    frontend:
        image: nginx:1.13
        volumes:
            # Site
            - ./web:/usr/share/nginx/html/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            # Configuração do proxy Reverso
        networks:
            - web
        depends_on:
            - app #Depende destas dependencias
    app:
        image: python:3.6
        volumes:
            # Aplicacao
            - ./app:/app
        working_dir: /app #Diretorio de execucao do comando
        command: bash ./app.sh #add bash pra dar permissao
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db #servico de banco de dados
            - queue
        environment:
            - DB_NAME=email_sender
    queue:
        image: redis:3.2
        networks:
            - fila
    worker:
        build: worker #Procura build na pasta worker, que sera minha imagem
        volumes:
            # Worker
            - ./worker:/worker
        working_dir: /worker
        command: ./worker.py #eh meu, entao n preciso de permissao
        networks:
            - fila
        depends_on:
            - queue